version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-container_workviser_aws
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
